### ISSUE TITLE
我想用10分钟线或者30分钟线计算最近一天的

### ISSUE THREAD

**Issue by liuts** [2892211452/ChipDistribution#3]
time  price  change  volume   amount type
0     09:25:04   7.87   -0.10    2443  1922641   卖盘
1     09:30:03   7.87    0.00     636   500120   卖盘
2     09:30:06   7.87    0.00     523   411353   买盘
3     09:30:10   7.87    0.00     389   306014   买盘
4     09:30:12   7.87    0.00     741   582160   买盘
。。。。。。。。。。。。。。。

我现在拿到的是这种数据，这种能不能计算筹码分布。这个数据缺少了换手 的那列的数据

**Comment by rusellwo** [comment]
talib ,you'll like it



------------------&nbsp;Original message&nbsp;------------------
From: "liuts"; 
Sendtime: Tuesday, Apr 6, 2021 1:52 PM
To: "2892211452/ChipDistribution"; 
Cc: "Subscribed"; 
Subject: Re: [2892211452/ChipDistribution] 我想用10分钟线或者30分钟线计算最近一天的 (#3)





 
Closed #3.
